package entertainment.games.enums;

public enum AccountReturnCode {
	PASSWORD_EXPIRED,
	ACCOUNT_SUSPENDED,
	LOGIN_SUCCESSFUL,
	INCORRECT_PASSWORD,
	INVALID_USER,
	ACCOUNT_ALREADY_EXISTS,
	ACCOUNT_CREATED,
	ACCOUNT_CREATION_ERROR
}
