package nutent.entertainment.web.enums;

public enum AccountReturnCode {
	PASSWORD_EXPIRED,
	ACCOUNT_LOCKED,
	LOGIN_SUCCESSFUL,
	INCORRECT_PASSWORD,
	INVALID_USER,
	ACCOUNT_ALREADY_EXISTS,
	ACCOUNT_CREATED,
	ACCOUNT_CREATION_ERROR,
	INVALID_PASSWORD,
	PASSWORD_MISMATCH,
	UNKNOWN_ERROR,
	PASSWORD_UPDATED
}
